Repository HGU-CRA/i-ticket, pull requests merged in 2018-07, with the labels that each got.

#3 edit README.md
  README.md
Labels: bug

#8 Icon recovery
  src/app/app.module.ts
  src/app/app.scss
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/seller-login/seller-login.html
  src/pages/seller-login/seller-login.scss
  src/pages/seller-login/seller-login.ts
  src/pages/seller-signup/seller-signup.html
  src/pages/seller-signup/seller-signup.scss
  src/pages/seller-signup/seller-signup.ts
  src/theme/variables.scss
Labels: back, bug, front

#11 [README] History 수정
  README.md
Labels: front

#10 Seller setting Page 수정.
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.scss
  src/pages/seller-setting/seller-setting.html
  src/pages/seller-setting/seller-setting.scss
  src/pages/seller-setting/seller-setting.ts
  src/theme/variables.scss
Labels: back, front

#18 비밀번호 찾기를 누를 때, 가입되어있지 않은 이메일일 경우 말해줄 워딩의 수정
  package-lock.json
  src/pages/seller-reset-pwd/seller-reset-pwd.ts
Labels: front
